{% set version = "0.2.2" %}

package:
  name: xarray-extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray-extras/xarray_extras-{{ version }}.tar.gz
  sha256: f3e93f4a37f29b4c596494deb1912aea3ae39d8afce0f7c931e5d3c568de785e

build:
  number: 0
  script: $PYTHON -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python {{ python }}
    - pip
    - {{ compiler('c') }}
  host:
    - python {{ python }}
  run:
    - python
    - dask >=0.17.3
    - numba >=0.34
    - numpy >=1.13
    - pandas >=0.20.2
    - scipy >=1.0.0
    - xarray >=0.10.0

test:
  imports:
    - xarray_extras
  requires:
    - pytest >=3.1

about:
  home: https://github.com/crusaderky/xarray_extras
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Advanced / experimental extensions to xarray'

extra:
  recipe-maintainers:
    - crusaderky
