{% set version = "0.5.0" %}

package:
  name: xarray-extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray-extras/xarray_extras-{{ version }}.tar.gz
  sha256: b4164811606e20d7d9cd3c55d4d28803b00fb0d5c9a34fce185472527deb6509

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - dask >=2021.4
    - numba >=0.52
    - numpy >=1.18
    - pandas >=1.1
    - scipy >=1.5
    - xarray >=0.16

test:
  imports:
    - xarray_extras
  requires:
    - pytest

about:
  home: https://github.com/crusaderky/xarray_extras
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: 'Advanced / experimental extensions to xarray'

extra:
  recipe-maintainers:
    - crusaderky
