{% set version = "0.2.0" %}

package:
  name: xarray-extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray-extras/xarray_extras-{{ version }}.tar.gz
  sha256: 45db2041e00581c912e92cdb071c93af025e2a3d49d0fbf6cd697dae3b690c41

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - dask >=0.17.3
    - numba >=0.34
    - numpy >=1.13
    - pandas >=0.20.2
    - scipy >=1.0.0
    - xarray >=0.10.0

test:
  imports:
    - xarray_extras
  requires:
    - pytest >=3.1

about:
  home: https://github.com/crusaderky/xarray_extras
  license: LGPL-3.0
  license_family: LGPL
  license_file: LICENSE
  summary: 'Advanced / experimental extensions to xarray'

extra:
  recipe-maintainers:
    - crusaderky
