{% set version = "0.6.0" %}

package:
  name: xarray-extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray-extras/xarray_extras-{{ version }}.tar.gz
  sha256: 825f86ecacfc5fd0e36f881ec974da9e8d1d7a5f6e0ede866142defddae4a749

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools >=66
    - setuptools-scm
    - pip
  run:
    - python
    - dask >=2022.6.0
    - numba >=0.56
    - numpy >=1.23
    - pandas >=1.5
    - scipy >=1.9
    - xarray >=2022.11.0

test:
  imports:
    - xarray_extras
  requires:
    - pytest

about:
  home: https://github.com/crusaderky/xarray_extras
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Advanced / experimental extensions to xarray'

extra:
  recipe-maintainers:
    - crusaderky
