{% set version = "0.4.2" %}

package:
  name: xarray-extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray-extras/xarray_extras-{{ version }}.tar.gz
  sha256: f458174d2adc66a947dbee6929242f56c1afa5a1c507b982d5ec4f4ee7e31e69

build:
  number: 1000
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - dask >=0.19
    - numba >=0.34
    - numpy >=1.13
    - pandas >=0.21
    - scipy >=1.0
    - xarray >=0.10.1

test:
  imports:
    - xarray_extras
  requires:
    - pytest >=3.6

about:
  home: https://github.com/crusaderky/xarray_extras
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: 'Advanced / experimental extensions to xarray'

extra:
  recipe-maintainers:
    - crusaderky
