{% set version = "0.3.0" %}

package:
  name: xarray-extras
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/x/xarray-extras/xarray_extras-{{ version }}.tar.gz
  sha256: 64c32a12f552ebed1bb8e121b5ecd95fa9d267b78bcb7ab3a5922c5c975a7383

build:
  number: 1001
  script: python -m pip install --no-deps --ignore-installed .
  skip: true  # [py27]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python
    - dask >=0.19
    - numba >=0.34
    - numpy >=1.13
    - pandas >=0.21
    - scipy >=1.0
    - xarray >=0.10.1

test:
  imports:
    - xarray_extras
  requires:
    - pytest >=3.6

about:
  home: https://github.com/crusaderky/xarray_extras
  license: Apache-2
  license_family: Apache
  license_file: LICENSE
  summary: 'Advanced / experimental extensions to xarray'

extra:
  recipe-maintainers:
    - crusaderky
