# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_c_compilerclangpython3.6
    - CONFIG=osx_c_compilerclangpython3.7
    - CONFIG=osx_c_compilertoolchain_cpython3.6
    - CONFIG=osx_c_compilertoolchain_cpython3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "jrYy0sFherdZHili/apSEGVb+gknA2oVnp5pX/cNBi3flucRvtUnsxRZ2b87OikCYBDtVar+r8GWQw3Ee1oLgZvjAkI6zT6D1LcjvScPTqjJRGoUraPL2QKhqo7nGxs5oPRsQCwoVOj+XAIoQgbW+u6lXxrKdSSfyUqyY13cviTqY57MWpOqpPDzgVAoptrQ9PehFIC5h3d+YP3JUuf7lkXc+L+E7PEXy5Th5QIb0Th4aXR3D5M+b1Kah7X0OK8XTZFdSGa8Tuxrsgz/EIuF/uUwFfgvEQj6G/HKlxH+giLeEnOgOOu069dXGgV9+iB5ZWmcHm59gCyFFK4elVvxl/USsgg7BD45RoU9cqhVcwyOg5AnB/Dz8Q6hag+3pI5M9g9lZdJlIaRIP7zVn1yjGGK80TTmjzomApr1peI64V1NK4Wv3aOh6T/nHKtgSM9E6Zsp2LNUAuk67i0F0+H8GAz6k+1HWTVUewDGTOzgkvatlZ4QcRKXe+cmBd3i4fNuSIdziuAIKxjxY7UIvKMHIrhGHg35MPoUGebIf5UIZyRIBzqdp2fVg+M720dSijJ4RiZ6mV7VWNBkPgFzf6tFDgynTq3E/DQDaE6Wtaivmu5+6uv6Ga2TdE8r61IEMEdDOm6Uu5uoVqMrAtu9rhec+5LS+Os53SjfWuaXkSG9YEM="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml