appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: jrYy0sFherdZHili/apSEGVb+gknA2oVnp5pX/cNBi3flucRvtUnsxRZ2b87OikCYBDtVar+r8GWQw3Ee1oLgZvjAkI6zT6D1LcjvScPTqjJRGoUraPL2QKhqo7nGxs5oPRsQCwoVOj+XAIoQgbW+u6lXxrKdSSfyUqyY13cviTqY57MWpOqpPDzgVAoptrQ9PehFIC5h3d+YP3JUuf7lkXc+L+E7PEXy5Th5QIb0Th4aXR3D5M+b1Kah7X0OK8XTZFdSGa8Tuxrsgz/EIuF/uUwFfgvEQj6G/HKlxH+giLeEnOgOOu069dXGgV9+iB5ZWmcHm59gCyFFK4elVvxl/USsgg7BD45RoU9cqhVcwyOg5AnB/Dz8Q6hag+3pI5M9g9lZdJlIaRIP7zVn1yjGGK80TTmjzomApr1peI64V1NK4Wv3aOh6T/nHKtgSM9E6Zsp2LNUAuk67i0F0+H8GAz6k+1HWTVUewDGTOzgkvatlZ4QcRKXe+cmBd3i4fNuSIdziuAIKxjxY7UIvKMHIrhGHg35MPoUGebIf5UIZyRIBzqdp2fVg+M720dSijJ4RiZ6mV7VWNBkPgFzf6tFDgynTq3E/DQDaE6Wtaivmu5+6uv6Ga2TdE8r61IEMEdDOm6Uu5uoVqMrAtu9rhec+5LS+Os53SjfWuaXkSG9YEM=}
provider:
  win: azure
