travis:
  secure:
    BINSTAR_TOKEN: M8FxSGViG1Hgnx2hjDVRKaXCxJCPMSSg8Q4CNUiLHVPzQWoBAL0JAtan6/cAtD/tUH82kA9ijRr+dqjLWWvbCqxoepFPcvJ+wJEFZunWCKTK3e7qTIy48GnXxVLt/iLsXTzHrApUjX4ZjkXDYb4GFyBsB0cT9i74Jl0Us7EI9Nfmocn18BGY/DV6X8Hni7uDQaPywGv0O/ReW75CJwhqTHSrOc92gtVCEItI2alO6l/uRZz29icPJWn6DNb5aLY2uIAG95x7JT81zJhWs51l2GDejJTSkKu7Dh1ihAQGNeNjLtlbyGyeuYEmqPojtBsDcSNTS9lbb1aUGeQVEIv7wbJV0XTz9kOAqbdRi08OPV9CuObnGBFvl+ItLhZE74skQgMLIw3C6wcG6PPuYH2mdgvXd4GkZdqhhm2GEFMk1wDw8JaXhKRjs+QLj+1vCg8Gtt2/Gmd5uM8URgoBqBV9NqtHwWXKcBn3WM1ZtgQLJjco1zKQ10Yhzd10yXQopMwAZOO8Z7dMEswJSBWWcJorWabTZfo1F+aC8uiLODQki71gaDZWJZoDSk4EwrqGSSaaIX2LdQmJsv7UrPXyF8NDEsGKnxSVLnxET9BEJVMZPjp12YNXBhboAH2moyane85A9n0UrnWdqjcoZJegFTNMjgJu1Kez+HRrgwb3M8T8600=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
